security:
    encoders:
        App\Entity\Client: plaintext
            #algorithm: argon2i
        App\Entity\Agency: plaintext
            #algorithm: argon2i
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        chain_provider:
            chain:
                providers: [in_memory, agency_provider, client_provider]
        in_memory:
            memory:
                users:
                    admin: {password: adminmdp, roles: ['ROLE_ADMIN']}
        client_provider:
            entity:
                class: App\Entity\Client
                property: email
        agency_provider:
            entity:
                class: App\Entity\Agency
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: chain_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            form_login:
                login_path: compte_connexion
                check_path: compte_connexion

            logout:
                path:   compte_deconnexion
                target: /

    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
