security:
    encoders:
        App\Entity\Client:
            algorithm: plaintext
        App\Entity\Agency:
            algorithm: argon2i
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        chain_provider:
            chain:
                providers: [in_memory, agency_provider, client_provider]
        in_memory:
            memory:
                users:
                    admin: {password: adminmdp, roles: ['ROLE_ADMIN']}
        client_provider:
            entity:
                class: App\Entity\Client
                property: email
        agency_provider:
            entity:
                class: App\Entity\Agency
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # main:
        #     anonymous: true
        #     guard:
        #         authenticators:
        #             - App\Security\LoginFormAuthenticator

        #     provider: app_user_provider

        #     form_login:
        #         login_path: compte_connexion
        #         check_path: compte_connexion

        #     logout:
        #         path: compte_deconnexion
        #         target: /

        main:
            provider: chain_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            # user_checker: App\Security\UserChecker

            form_login:
                login_path: compte_connexion
                check_path: compte_connexion

            logout:
                path:   compte_deconnexion
                target: /

            # remember_me:
            #     secret:   '%kernel.secret%'
            #     lifetime: 604800 # 1 week in seconds
            #     path:     /

        # agency_secured_domain:
        #     provider: agency_provider
        #     anonymous: true
        #     guard:
        #         authenticators:
        #             - App\Security\LoginFormAuthenticator
        #     # user_checker: App\Security\UserChecker

        #     form_login:
        #         login_path: compte_connexion
        #         check_path: compte_connexion

        #     logout:
        #         path:   compte_deconnexion
        #         target: /

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
