vich_uploader:
    db_driver: orm

    mappings:
        agency_images:
            uri_prefix: '%app.path.agency_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.agency_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        client_images:
            uri_prefix: '%app.path.client_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.client_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
        documents_images:
            uri_prefix: '%app.path.documents_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.documents_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer