vich_uploader:
    db_driver: orm

    mappings:
        agency_images:
            uri_prefix: '%app.path.agency_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.agency_images%'
        
        client_images:
            uri_prefix: '%app.path.client_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.client_images%'

        stages_images:
            uri_prefix: '%app.path.stages_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.stages_images%'