vich_uploader:
    db_driver: orm

    mappings:
        agency_images:
            uri_prefix: '%app.path.agency_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.agency_images%'