language: php
php:
    - '7.2'
before_install:
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [ -d "./.idea" ]; then echo "Forbidden idea folder found ! Please, ignore them globaly..."; exit 2; fi
    - if [ -d "./.env.local" ]; then echo "Forbidden configuration file found !"; exit 2; fi
    - if [ -d "./vendor" ]; then echo "Forbidden external libs folder found !"; exit 2; fi
    - if [ -d ".DS_Store" ]; then echo "Forbidden MacOS boring file found ! Please, ignore them globaly..."; exit 2; fi
install:
    - composer require squizlabs/php_codesniffer
    - composer require phpstan/phpstan
    #- composer require phpunit
script:
    - ./bin/phpcs
    - ./bin/phpstan analyse src --level 5
    #- ./bin/phpunit
notifications:
    email:
        - francois.doussin@wildcodeschool.fr
        - Vincent_Mallard_student2019@wilder.school 
branches:
    only:
        - master
        - dev
